import { BUSINESS_CHARTER } from './BusinessOrientationCharter.mjs';

const clamp=value=>Math.max(0,Math.min(1,Number(value)||0));
const finite=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const clone=value=>structuredClone(value);

function horizon(item){if(item.speculative||finite(item.evidence)<.25)return 'speculative';if(item.recurring)return 'recurring-income';if(finite(item.timeToCashHours,Infinity)<=72)return 'quick-cash';return 'long-term-venture';}
function weights(context){const target=Math.max(1,finite(context.cashTarget,1)),shortfall=Math.max(0,target-finite(context.cashAvailable)),urgency=clamp(context.cashUrgency??shortfall/target),recurrence=clamp(context.recurringIncomeNeed),riskProtection=1-clamp(context.riskTolerance??.25);const raw={urgency,capitalFit:clamp(shortfall/target),evidence:clamp(.5+riskProtection/2),readiness:clamp(.5+urgency/2),return:clamp(.5+urgency/2),recurrence,risk:riskProtection};const total=Object.values(raw).reduce((sum,value)=>sum+value,0)||1;return Object.freeze(Object.fromEntries(Object.entries(raw).map(([key,value])=>[key,value/total])));}

export class BusinessOrientationEngine {
  constructor({clock=()=>Date.now()}={}){this.clock=clock;this.decisions=[];this.outcomes=[];}
  evaluate(opportunities=[],context={}){const activeWeights=weights(context),availableCash=finite(context.cashAvailable),deadline=finite(context.deadlineHours,Infinity);const evaluated=opportunities.map(item=>{const cost=Math.max(0,finite(item.upfrontCost)),revenue=Math.max(0,finite(item.expectedRevenue)),hours=Math.max(.25,finite(item.timeHours,1)),toCash=Math.max(0,finite(item.timeToCashHours,Infinity)),risk=clamp(item.risk),evidence=clamp(item.evidence),readiness=clamp(item.readiness),net=revenue-cost;const factors={urgency:deadline===Infinity?clamp(1/(1+toCash/72)):clamp((deadline-toCash)/Math.max(1,deadline)),capitalFit:cost<=availableCash?1:clamp(availableCash/Math.max(1,cost)),evidence,readiness,return:clamp(net/Math.max(1,Math.abs(net)+hours*10)),recurrence:item.recurring?1:0,risk:1-risk};const score=Object.entries(activeWeights).reduce((sum,[key,weight])=>sum+weight*factors[key],0);const risks=[];if(cost>availableCash)risks.push('insufficient-available-cash');if(evidence<.5)risks.push('weak-market-evidence');if(risk>.6)risks.push('high-operational-or-reputational-risk');if((item.dependencies??[]).length)risks.push('unresolved-dependencies');return Object.freeze({...clone(item),horizon:horizon(item),economics:Object.freeze({cost,revenue,net,hours,timeToCashHours:toCash}),factors:Object.freeze(factors),score,risks:Object.freeze(risks),approvalRequired:Object.freeze((item.actions??[]).filter(action=>BUSINESS_CHARTER.bindingApproval.includes(action)))});}).toSorted((a,b)=>b.score-a.score||a.economics.timeToCashHours-b.economics.timeToCashHours||String(a.id).localeCompare(String(b.id)));const record=Object.freeze({id:`business-decision:${this.decisions.length+1}`,at:this.clock(),context:clone(context),weights:activeWeights,ranked:Object.freeze(evaluated)});this.decisions.push(record);return record;}
  recordOutcome({decisionId,opportunityId,revenue=0,cost=0,hours=0,result='unknown',evidence={}}={}){if(!this.decisions.some(item=>item.id===decisionId))throw new Error('BUSINESS_DECISION_NOT_FOUND');const record=Object.freeze({id:`business-outcome:${this.outcomes.length+1}`,at:this.clock(),decisionId,opportunityId,result,revenue:finite(revenue),cost:finite(cost),hours:finite(hours),net:finite(revenue)-finite(cost),evidence:clone(evidence)});this.outcomes.push(record);return record;}
  explain(decision){return Object.freeze(decision.ranked.map((item,index)=>Object.freeze({rank:index+1,id:item.id,horizon:item.horizon,reason:Object.freeze({score:item.score,weights:decision.weights,factors:item.factors,risks:item.risks}),approvalRequired:item.approvalRequired})));}
  snapshot(){return Object.freeze({decisions:clone(this.decisions),outcomes:clone(this.outcomes)});}
  restore(snapshot){this.decisions=(snapshot?.decisions??[]).map(item=>Object.freeze(item));this.outcomes=(snapshot?.outcomes??[]).map(item=>Object.freeze(item));return this;}
}
