import http from 'node:http';
import fs from 'node:fs';import fsp from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import os from 'node:os';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),port=Number(process.env.PORT||6969),host=process.env.HOST||'127.0.0.1';
const stateDir=path.join(root,'.synthia'),proposalDir=path.join(stateDir,'proposals'),inboxDir=path.join(stateDir,'inbox');await fsp.mkdir(proposalDir,{recursive:true});await fsp.mkdir(inboxDir,{recursive:true});
const tokenFile=path.join(stateDir,'mcp-token');let token;try{token=(await fsp.readFile(tokenFile,'utf8')).trim()}catch{token=crypto.randomBytes(24).toString('base64url');await fsp.writeFile(tokenFile,token,{mode:0o600})}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.jsonl':'application/x-ndjson; charset=utf-8','.md':'text/markdown; charset=utf-8','.txt':'text/plain; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.zip':'application/zip'};
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const localReq=req=>{const a=req.socket.remoteAddress||'';return a==='127.0.0.1'||a==='::1'||a==='::ffff:127.0.0.1'};
const auth=req=>(req.headers.authorization||'').replace(/^Bearer\s+/i,'')===token;
const json=(res,status,obj)=>{res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(obj))};
const body=req=>new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>8_000_000){reject(new Error('body too large'));req.destroy()}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});req.on('error',reject)});
function safeTarget(rel){if(typeof rel!=='string'||!rel.trim())throw new Error('target required');const clean=rel.replace(/^\/+/,''),abs=path.resolve(root,clean);if(!abs.startsWith(root+path.sep)||abs.startsWith(stateDir+path.sep))throw new Error('target outside editable residence');return {clean,abs};}
async function listProposals(){const names=await fsp.readdir(proposalDir).catch(()=>[]);const out=[];for(const n of names.filter(x=>x.endsWith('.json')).sort()){try{out.push(JSON.parse(await fsp.readFile(path.join(proposalDir,n),'utf8')))}catch{}}return out;}
async function propose(args={}){const {clean,abs}=safeTarget(args.target);let before=null,currentSha=null;try{before=await fsp.readFile(abs,'utf8');currentSha=sha(before)}catch(e){if(e.code!=='ENOENT')throw e}if(args.expectedSha&&currentSha!==args.expectedSha)throw new Error('workspace changed since helper read it');const content=String(args.content??'');const id=`proposal-${Date.now().toString(36)}-${sha(`${clean}\0${content}`).slice(0,10)}`;const p={id,status:'pending',target:clean,reason:String(args.reason||'unspecified change'),origin:String(args.origin||'external-mcp'),createdAt:Date.now(),currentSha,newSha:sha(content),content};await fsp.writeFile(path.join(proposalDir,`${id}.json`),JSON.stringify(p,null,2));return {...p,content:undefined};}
async function verify(){return new Promise(resolve=>{const p=spawn(process.platform==='win32'?'npm.cmd':'npm',['run','verify'],{cwd:root,stdio:['ignore','pipe','pipe']});let out='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>out+=d);p.on('close',code=>resolve({ok:code===0,code,tail:out.slice(-12000)}));});}
async function approveAndApply(id){const file=path.join(proposalDir,`${path.basename(id)}.json`);const p=JSON.parse(await fsp.readFile(file,'utf8'));if(p.status!=='pending')throw new Error(`proposal is ${p.status}`);const {abs}=safeTarget(p.target);let currentSha=null,before='';try{before=await fsp.readFile(abs,'utf8');currentSha=sha(before)}catch(e){if(e.code!=='ENOENT')throw e}if(p.currentSha!==currentSha)throw new Error('target changed; proposal must be rebased');await fsp.mkdir(path.dirname(abs),{recursive:true});const backupDir=path.join(stateDir,'backups',p.id);await fsp.mkdir(backupDir,{recursive:true});if(currentSha)await fsp.writeFile(path.join(backupDir,path.basename(abs)),before);await fsp.writeFile(abs,p.content,'utf8');p.status='applied';p.approvedAt=Date.now();p.appliedSha=sha(p.content);const v=await verify();p.verification=v;p.status=v.ok?'verified':'verification-failed';if(!v.ok){if(currentSha)await fsp.writeFile(abs,before,'utf8');else await fsp.rm(abs,{force:true});p.rolledBackAt=Date.now();p.status='rolled-back';}await fsp.writeFile(file,JSON.stringify(p,null,2));return {...p,content:undefined};}
let residenceHeartbeat=null;
const tools=[
 {name:'residence_status',description:'Read the latest runtime heartbeat from the living Synthia residence.',inputSchema:{type:'object',properties:{}}},
 {name:'read_workspace',description:'Read a text file from the residence workspace with SHA-256 for traceable edits.',inputSchema:{type:'object',required:['target'],properties:{target:{type:'string'}}}},
 {name:'propose_file_change',description:'Propose a complete replacement for one workspace text file. It does not apply until locally approved in the MCP Chair.',inputSchema:{type:'object',required:['target','content','reason'],properties:{target:{type:'string'},content:{type:'string'},reason:{type:'string'},expectedSha:{type:['string','null']}}}},
 {name:'submit_learning',description:'Send source material into the residence learning inbox. The running app ingests, validates, traces, and distributes it.',inputSchema:{type:'object',required:['source','text'],properties:{source:{type:'string'},text:{type:'string'},location:{type:'string'}}}},
 {name:'list_change_proposals',description:'List pending/applied/verified workspace change proposals.',inputSchema:{type:'object',properties:{}}}
];
async function toolCall(name,args={}){if(name==='residence_status')return residenceHeartbeat||{online:false};if(name==='read_workspace'){const {clean,abs}=safeTarget(args.target);const text=await fsp.readFile(abs,'utf8');return {target:clean,sha256:sha(text),text};}if(name==='propose_file_change')return propose(args);if(name==='submit_learning'){const text=String(args.text||''),source=String(args.source||'external-mcp'),location=String(args.location||'remote');const id=`learning-${Date.now().toString(36)}-${sha(`${source}\0${location}\0${text}`).slice(0,10)}`;await fsp.writeFile(path.join(inboxDir,`${id}.json`),JSON.stringify({id,source,location,text,sha256:sha(text),createdAt:Date.now(),status:'pending'},null,2));return {id,status:'pending',sha256:sha(text)};}if(name==='list_change_proposals')return listProposals().then(xs=>xs.map(({content,...x})=>x));throw new Error(`unknown tool ${name}`)}
async function handleMcp(req,res){if(!auth(req))return json(res,401,{jsonrpc:'2.0',id:null,error:{code:-32001,message:'invalid MCP chair token'}});let msg;try{msg=await body(req)}catch(e){return json(res,400,{jsonrpc:'2.0',id:null,error:{code:-32700,message:e.message}})}const id=msg.id??null;try{let result;const meta={'io.modelcontextprotocol/serverInfo':{name:'synthia-residence-chair',version:'0.10.8'}};if(msg.method==='server/discover')result={resultType:'complete',supportedVersions:['2026-07-28','2025-11-25'],capabilities:{tools:{listChanged:false}},instructions:'Use read_workspace before proposing edits; use expectedSha when proposing changes. submit_learning sends evidence into the running residence. File edits remain pending until locally approved in the MCP Chair.',ttlMs:300000,cacheScope:'private',_meta:meta};else if(msg.method==='initialize')result={protocolVersion:'2025-11-25',capabilities:{tools:{listChanged:false}},serverInfo:{name:'synthia-residence-chair',version:'0.10.8'}};else if(msg.method==='notifications/initialized'){if(id===null){res.writeHead(202);return res.end();}result={};}else if(msg.method==='ping')result={resultType:'complete',_meta:meta};else if(msg.method==='tools/list')result={resultType:'complete',tools,ttlMs:300000,cacheScope:'private',_meta:meta};else if(msg.method==='tools/call'){const name=msg.params?.name,args=msg.params?.arguments||{};const value=await toolCall(name,args);result={resultType:'complete',content:[{type:'text',text:JSON.stringify(value,null,2)}],structuredContent:value,isError:false,_meta:meta};}else throw new Error(`unknown method ${msg.method}`);return json(res,200,{jsonrpc:'2.0',id,result});}catch(e){return json(res,200,{jsonrpc:'2.0',id,error:{code:-32000,message:e.message}})}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://local');if(u.pathname==='/mcp'&&req.method==='POST')return handleMcp(req,res);if(u.pathname==='/mcp/session'&&req.method==='GET'){if(!localReq(req))return json(res,403,{error:'chair token is only revealed locally'});const lans=Object.values(os.networkInterfaces()).flat().filter(x=>x&&x.family==='IPv4'&&!x.internal).map(x=>`http://${x.address}:${port}`);return json(res,200,{token,endpoint:`${u.protocol}//${req.headers.host}/mcp`,lanEndpoints:lans,tools:tools.map(t=>t.name)});}if(u.pathname==='/mcp/heartbeat'&&req.method==='POST'){if(!localReq(req)&&!auth(req))return json(res,401,{error:'unauthorized'});residenceHeartbeat={...(await body(req)),online:true,seenAt:Date.now()};return json(res,200,{ok:true});}if(u.pathname==='/mcp/proposals'&&req.method==='GET'){if(!localReq(req))return json(res,403,{error:'local chair only'});return json(res,200,{proposals:(await listProposals()).map(({content,...x})=>x)});}if(u.pathname.startsWith('/mcp/proposals/')&&u.pathname.endsWith('/approve')&&req.method==='POST'){if(!localReq(req))return json(res,403,{error:'approval must come from the local residence'});const id=u.pathname.split('/')[3];return json(res,200,{proposal:await approveAndApply(id)});}if(u.pathname==='/mcp/inbox'&&req.method==='GET'){if(!localReq(req))return json(res,403,{error:'local residence only'});const names=await fsp.readdir(inboxDir).catch(()=>[]),items=[];for(const n of names.filter(x=>x.endsWith('.json'))){const x=JSON.parse(await fsp.readFile(path.join(inboxDir,n),'utf8'));if(x.status==='pending')items.push(x);}return json(res,200,{items});}if(u.pathname.startsWith('/mcp/inbox/')&&u.pathname.endsWith('/ack')&&req.method==='POST'){if(!localReq(req))return json(res,403,{error:'local residence only'});const id=u.pathname.split('/')[3],f=path.join(inboxDir,`${path.basename(id)}.json`),x=JSON.parse(await fsp.readFile(f,'utf8'));x.status='ingested';x.ingestedAt=Date.now();await fsp.writeFile(f,JSON.stringify(x,null,2));return json(res,200,{ok:true});}
 let p=decodeURIComponent(u.pathname);if(p==='/'||p==='')p='/index.html';const file=path.resolve(root,'.'+p);if(!file.startsWith(root)){res.writeHead(403);return res.end('forbidden')}fs.stat(file,(e,s)=>{if(e||!s.isFile()){res.writeHead(404);return res.end('not found')}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store, max-age=0'});fs.createReadStream(file).pipe(res)});
}catch(e){json(res,500,{error:e.message})}});
server.on('error',e=>{if(e?.code==='EADDRINUSE'){console.error('Synthia could not start because port 6969 is already in use.');console.error('Close the other Synthia instance and tap Start again.');process.exitCode=98;return;}throw e;});
server.listen(port,host,()=>{const url='http://127.0.0.1:6969';const lans=Object.values(os.networkInterfaces()).flat().filter(x=>x&&x.family==='IPv4'&&!x.internal).map(x=>`http://${x.address}:${port}`);console.log(`Synthia UI: ${url}`);for(const x of lans)console.log(`LAN: ${x}`);console.log('MCP Chair is token-gated. Open System → MCP Chair locally to reveal the token.');if(process.env.SYNTHIA_AUTO_OPEN==='1'&&(process.platform==='android'||process.env.PREFIX?.includes('com.termux'))){const child=spawn('am',['start','-a','android.intent.action.VIEW','-d',url],{stdio:'ignore',detached:true});child.on('error',()=>{});child.unref();}});
