import assert from 'node:assert/strict';
import SynthiaUnit from '../core/SynthiaUnit.mjs';
const store=new Map();
globalThis.localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const a=new SynthiaUnit({profile:{id:'adaya'}});
const first=await a.ask('analyze gate 42 and remember this result');
assert.equal(first.ok,true);
assert.ok(first.address?.gate>=1 && first.address?.gate<=64);
assert.ok(first.graphSteps>=1);
assert.ok(first.activeTools.includes('morph-mir'));
assert.ok(first.route.length>=1);
const snap1=a.snapshot();
assert.ok((snap1.memory.events||[]).length>=1);
const b=new SynthiaUnit({profile:{id:'adaya'}});
const snap2=b.snapshot();
assert.ok((snap2.memory.events||[]).length>=1,'persisted events should reload');
const next=await b.autonomousCycle({intent:'continue analyzing gate 42'});
assert.equal(next.ok,true);
assert.equal(next.autonomous,true);
assert.ok(next.graphSteps>=1);
assert.ok(next.activeTools.includes('morph-mir'));
console.log(JSON.stringify({pass:true,boot:true,ingest:true,address:true,route:true,toolExecution:true,learn:true,persist:true,reload:true,continue:true,activeTools:next.activeTools.length}));
