"""
field_scales.py — computational value of a hexagram AT SCALE.

Ports the JS lattice math (field_core.js) to Python, non-motor layer,
per the locked JS-first/Python-second split. Implements §0's master
principle directly: a gate has no fixed value in isolation — its value
is generated by intermingling dimensions, and that intermingling is
computed differently at each scale.
"""

import math

# ── LATTICE CONSTANTS (ported from field_core.js) ──────────────────────────
GATES = 64
LINES_PER_GATE = 6
COLORS_PER_LINE = 6
TONES_PER_COLOR = 6
BASES_PER_TONE = 5
ARC_PER_GATE = 360 / GATES  # 5.625°
ARCSEC_PER_GATE = round(ARC_PER_GATE * 3600)  # 20,250

# Base -> dimension mapping (locked spec §3)
BASE_TO_DIMENSION = {
    4: "Ego",           # Design
    3: "Body",          # Being
    1: "Individuality",  # Movement
    2: "Mind",           # Evolution
    5: "Personality",    # Space
}

# ── CRYSTAL / MONOPOLE GROUPING (locked §3.1) ───────────────────────────────
CRYSTAL_GROUPS = {
    "Personality Crystal": ("Personality", "Mind"),   # Space + Evolution
    "Design Crystal": ("Body", "Ego"),                 # Being + Design
    "Monopole": ("Individuality",),                    # Movement, unpaired
}

# ── NATURE CHAINS (macrocosmic + microcosmic, from reference images) ───────
MACRO_CHAINS = {
    "Individuality": ["Movement", "Energy", "Creation", "Seeing", "Landscape", "Environment"],
    "Mind":           ["Evolution", "Gravity", "Memory", "Taste", "Love", "Light"],
    "Body":           ["Being", "Matter", "Touch", "Sex", "Survival"],
    "Ego":            ["Design", "Structure", "Progress", "Smell", "Life", "Art"],
    "Personality":    ["Space", "Form", "Illusion", "Hearing", "Music", "Freedom"],
}


def positionToAddress(longitude_deg: float) -> dict:
    """Same math as field_core.js positionToAddress — integer arcsecond, no float recursion.

    NOTE: the 1-64 value this produces is a SEQUENTIAL lattice slot (slot 1
    at 0 deg, slot 64 at 354.375 deg) -- it is NOT the traditional Human
    Design gate number, which follows a specific non-sequential wheel order
    starting at Gate 41 (302 deg), already correctly implemented and
    validated against SharpAstrology in hd_engine.py. Named 'lattice_slot'
    here, not 'gate', to avoid the same kind of naming collision already
    flagged and fixed for Base/FUSE in spec section 1.3. If a real HD gate
    number is needed, get it from hd_engine.py's wheel-order function --
    this module's job is the intermingling/scale math, not gate identity.
    """
    pos = ((longitude_deg % 360) + 360) % 360
    gate_float = pos / ARC_PER_GATE
    lattice_slot = int(math.floor(gate_float)) + 1

    within_gate = (gate_float - math.floor(gate_float)) * LINES_PER_GATE
    line = int(math.floor(within_gate)) + 1

    within_line = (within_gate - math.floor(within_gate)) * COLORS_PER_LINE
    color = int(math.floor(within_line)) + 1

    within_color = (within_line - math.floor(within_line)) * TONES_PER_COLOR
    tone = int(math.floor(within_color)) + 1

    within_tone = (within_color - math.floor(within_color)) * BASES_PER_TONE
    base = int(math.floor(within_tone)) + 1

    deg_within_gate = pos - (lattice_slot - 1) * ARC_PER_GATE
    arcsecond = round(deg_within_gate * 3600)

    return {
        "longitude": pos, "lattice_slot": lattice_slot, "line": line,
        "color": color, "tone": tone, "base": base,
        "arcsecond": arcsecond
    }


def intermingle(dim_a: str, dim_b: str) -> str:
    """
    THE core mechanism (§0): combine two dimensions' Nature chains into
    one interpretation, rather than reading either dimension alone.
    Simple version: interleave the two chains to show how they cross.
    """
    chain_a = MACRO_CHAINS[dim_a]
    chain_b = MACRO_CHAINS[dim_b]
    crossed = []
    for i in range(max(len(chain_a), len(chain_b))):
        if i < len(chain_a):
            crossed.append(chain_a[i])
        if i < len(chain_b):
            crossed.append(chain_b[i])
    return " <-> ".join(crossed)


def hexagram_value_at_scale(longitude_deg: float, scale: str) -> dict:
    """
    Compute a gate's value at one of the locked scales. No fixed lookup —
    every scale computes its value by intermingling, per §0.
    """
    addr = positionToAddress(longitude_deg)

    if scale == "macrocosmic":
        # Intermingle the two paired dimensions of whichever Crystal the
        # gate's Base falls under; Monopole has nothing to pair, so it
        # stands alone as the channel-value (§3.1).
        dim = BASE_TO_DIMENSION[addr["base"]]
        for crystal, dims in CRYSTAL_GROUPS.items():
            if dim in dims:
                if len(dims) == 2:
                    value = intermingle(dims[0], dims[1])
                else:
                    value = f"[MONOPOLE — channel site] {MACRO_CHAINS[dim][0]}"
                return {"scale": scale, "crystal": crystal, "value": value}

    elif scale == "gate_line":
        value = f"Slot {addr['lattice_slot']} intermingling Line {addr['line']} " \
                f"(structural identity x transition)"
        return {"scale": scale, "value": value}

    elif scale == "color_tone_base":
        value = f"Color {addr['color']} intermingling Tone {addr['tone']} " \
                f"intermingling Base {addr['base']}"
        return {"scale": scale, "value": value}

    elif scale == "arcsecond":
        value = f"Arcsecond {addr['arcsecond']} — fine differential point, " \
                f"self-intermingling at maximum resolution"
        return {"scale": scale, "value": value}

    return {"scale": scale, "value": None, "note": "unrecognized scale"}


def positionToColor(longitude_deg: float) -> dict:
    """Same math as field_core.js positionToColor — hue is a direct circular
    readout of longitude, not a separate stored table."""
    hue = ((longitude_deg % 360) + 360) % 360
    return {"hue": round(hue, 2), "css": f"hsl({hue:.2f}, 70%, 55%)"}


def positionToFrequency(address: dict, base_freq: float = 110, octave_span: float = 110) -> float:
    """
    CORRECTED: frequency comes from TONE, not raw longitude in isolation.
    "Music is where the tone comes" — Tone (1-6) selects the base pitch
    (like a scale degree), and the fine arcsecond position modulates
    within that tone's band. This is also why "Hearing is Music" sits in
    the Personality/Space Nature chain specifically — Tone is the
    connective link between the lattice and sound, not longitude alone.
    """
    tone = address["tone"]  # 1-6
    tone_band_width = octave_span / TONES_PER_COLOR
    tone_base = base_freq + (tone - 1) * tone_band_width

    # Fine modulation within the tone's band, from arcsecond position
    arcsec_fraction = address["arcsecond"] / ARCSEC_PER_GATE
    return tone_base + arcsec_fraction * tone_band_width


def read_node_full(longitude_deg: float) -> dict:
    """
    THE closed loop: one longitude produces address, intermingled MEANING
    (macrocosmic scale), AND sensory expression (color + sound) — all from
    the same filter, none of it stored separately. This is where "Art" in
    the intermingled chain actually becomes a color and a frequency, not
    just a word sitting next to other words.
    """
    addr = positionToAddress(longitude_deg)
    return {
        "address": addr,
        "meaning": hexagram_value_at_scale(longitude_deg, "macrocosmic"),
        "color": positionToColor(longitude_deg),
        "frequency_hz": round(positionToFrequency(addr), 2)
    }


if __name__ == "__main__":
    test_longitude = 302.1
    scales = ["macrocosmic", "gate_line", "color_tone_base", "arcsecond"]

    addr = positionToAddress(test_longitude)
    print(f"Address for {test_longitude}°: Slot {addr['lattice_slot']}.{addr['line']} "
          f"C{addr['color']} T{addr['tone']} B{addr['base']} arcsec={addr['arcsecond']}\n")

    for s in scales:
        result = hexagram_value_at_scale(test_longitude, s)
        print(f"[{s}]")
        for k, v in result.items():
            if k != "scale":
                print(f"  {k}: {v}")
        print()

    print("=" * 60)
    print("CLOSED LOOP: meaning -> color -> sound, same longitude")
    print("=" * 60)
    full = read_node_full(test_longitude)
    print(f"Slot: {full['address']['lattice_slot']}.{full['address']['line']}")
    print(f"Meaning (Crystal: {full['meaning']['crystal']}):")
    print(f"  {full['meaning']['value']}")
    print(f"Color: {full['color']['css']}  (hue {full['color']['hue']}°)")
    print(f"Sound: {full['frequency_hz']} Hz")


# ── BIT ENCODING + MULTI-LEVEL CHANNEL EMERGENCE (ported from field_core.js) ──
# Same math as the JS version. This was the missing half of the port --
# field_scales.py had the address/color/frequency/intermingle functions but
# not the Hamming-distance-1 channel emergence logic, which is the single
# most spec-critical rule ("exactly where the last build failed" per the
# spec). Ported here in pure Python -- no server, no bridge to the JS file;
# both are independent, correct implementations of the same locked math.

def address_to_bits(lattice_slot: int, line: int, color: int, tone: int, base: int) -> int:
    """Encode an address as an 18-bit vector: 6-bit slot (0-63), 3-bit line,
    3-bit color, 3-bit tone, 3-bit base (5 values fit in 3 bits)."""
    g = (lattice_slot - 1) & 0b111111
    l = (line - 1) & 0b111
    c = (color - 1) & 0b111
    t = (tone - 1) & 0b111
    b = (base - 1) & 0b111
    return (g << 12) | (l << 9) | (c << 6) | (t << 3) | b


def level_bits(lattice_slot: int, line: int, color: int, tone: int, base: int) -> dict:
    """Split bits by structural LEVEL so emergence can be checked
    independently at each level, not as one flat comparison."""
    return {
        "slot_line": ((lattice_slot - 1) & 0b111111) << 3 | ((line - 1) & 0b111),
        "color_tone_base": ((color - 1) & 0b111) << 6 | ((tone - 1) & 0b111) << 3 | ((base - 1) & 0b111),
    }


def arcsec_level_bits(arcsec_within_slot: int) -> int:
    """Fine-level (degree/minute/second within the slot) split for its own
    independent emergence check."""
    deg = (arcsec_within_slot // 3600) & 0b111
    rem_after_deg = arcsec_within_slot - deg * 3600
    minute = (rem_after_deg // 60) & 0b111111
    sec = int(rem_after_deg - minute * 60) & 0b111111
    return (deg << 12) | (minute << 6) | sec


def hamming_distance(bits_a: int, bits_b: int) -> int:
    x = bits_a ^ bits_b
    count = 0
    while x:
        count += x & 1
        x >>= 1
    return count


def channel_emerges(address_a: dict, address_b: dict) -> dict:
    """A channel can arise independently at ANY structural level via
    Hamming-distance-1 within that level's own bits -- Slot/Line is one
    emergence site, Color/Tone/Base is a separate site, arcsecond is a
    third. A fine-arc-level channel does not require a Slot-level channel
    to also be present, and vice versa. Matches field_core.js's
    channelEmerges exactly."""
    levels_a = level_bits(address_a["lattice_slot"], address_a["line"], address_a["color"], address_a["tone"], address_a["base"])
    levels_b = level_bits(address_b["lattice_slot"], address_b["line"], address_b["color"], address_b["tone"], address_b["base"])

    slot_line = hamming_distance(levels_a["slot_line"], levels_b["slot_line"]) == 1
    color_tone_base = hamming_distance(levels_a["color_tone_base"], levels_b["color_tone_base"]) == 1

    arcsecond = False
    if address_a.get("arcsecond") is not None and address_b.get("arcsecond") is not None:
        arc_a = arcsec_level_bits(address_a["arcsecond"])
        arc_b = arcsec_level_bits(address_b["arcsecond"])
        arcsecond = hamming_distance(arc_a, arc_b) == 1

    return {
        "any": slot_line or color_tone_base or arcsecond,
        "slot_line": slot_line, "color_tone_base": color_tone_base, "arcsecond": arcsecond,
    }
