const clean=s=>String(s??'').trim();
const ident=s=>clean(s).replace(/[^A-Za-z0-9_$]/g,'_').replace(/^([0-9])/,'_$1')||'generatedCapability';
const hash=s=>{let h1=2166136261,h2=0x9e3779b9;for(const c of String(s)){const n=c.charCodeAt(0);h1^=n;h1=Math.imul(h1,16777619);h2^=n+((h2<<6)>>>0)+(h2>>>2);h2>>>=0;}const base=((h1>>>0).toString(16).padStart(8,'0')+(h2>>>0).toString(16).padStart(8,'0'));return base.repeat(4);};
const byteLength=s=>typeof TextEncoder!=='undefined'?new TextEncoder().encode(String(s)).length:String(s).length;
const uniq=a=>[...new Set(a)];
const importsOf=source=>uniq([...String(source||'').matchAll(/(?:import\s+(?:[^'";]+?\s+from\s+)?|require\s*\(\s*)['"]([^'"]+)['"]/g)].map(m=>m[1]));
const exportsOf=source=>uniq([...String(source||'').matchAll(/export\s+(?:default\s+)?(?:class|function|const|let|var)?\s*([A-Za-z_$][\w$]*)?/g)].map(m=>m[1]).filter(Boolean));
/**
 * Sovereign code-construction process. It can inspect, plan, synthesize,
 * repair, and emit a bounded multi-file change set without SynthiaUnit.
 * Adoption remains the responsibility of mutation/verification processes.
 */
export class AutoCoder{
  constructor({name='AutoCoder',maxFiles=32,maxSourceBytes=512_000}={}){this.name=name;this.maxFiles=maxFiles;this.maxSourceBytes=maxSourceBytes;this.history=[];}
  inspectProject(files=[]){
    if(!Array.isArray(files)) throw new TypeError('files must be an array');
    const normalized=files.slice(0,this.maxFiles).map((file,index)=>{const path=clean(file.path)||`file-${index}`;const source=String(file.source??file.content??'').slice(0,this.maxSourceBytes);return Object.freeze({path,bytes:byteLength(source),hash:hash(source),imports:Object.freeze(importsOf(source)),exports:Object.freeze(exportsOf(source)),source});});
    const internal=new Set(normalized.map(f=>'./'+f.path.replace(/\.(mjs|js|ts)$/,'')));
    const dependencies=uniq(normalized.flatMap(f=>f.imports));
    return Object.freeze({files:Object.freeze(normalized),fileCount:normalized.length,totalBytes:normalized.reduce((n,f)=>n+f.bytes,0),dependencies:Object.freeze(dependencies),externalDependencies:Object.freeze(dependencies.filter(d=>!d.startsWith('.')&&!internal.has(d)))});
  }
  planChange({goal,project,capabilities=[],constraints=[],targetFiles=[]}={}){
    const inspection=project?.files?project:this.inspectProject(project||[]);
    const targets=targetFiles.length?targetFiles:inspection.files.slice(0,Math.min(4,inspection.files.length)).map(f=>f.path);
    return Object.freeze({id:`plan:${hash(JSON.stringify({goal,targets,capabilities,constraints})).slice(0,16)}`,goal:clean(goal),targets:Object.freeze([...targets]),capabilities:Object.freeze(uniq(capabilities.map(String))),constraints:Object.freeze(uniq(constraints.map(String))),dependencies:inspection.dependencies,steps:Object.freeze(['inspect existing contracts','reuse resident modules before creating new ones','synthesize bounded changes','emit tests','hand off to mutation process','adopt only after verification'])});
  }
  synthesize(spec={}){const name=ident(spec.name||spec.capability||'generatedCapability');const inputs=Array.isArray(spec.inputs)?spec.inputs.map(ident):[];const body=clean(spec.body)||`return { ok: true, capability: ${JSON.stringify(name)}, input: { ${inputs.join(', ')} } };`;const source=`/** Generated by ${this.name}. Functional candidate; verification required before adoption. */\nexport function ${name}(${inputs.join(', ')}) {\n  ${body.replace(/\n/g,'\n  ')}\n}\nexport default ${name};\n`;const rec={id:`code:${hash(source).slice(0,16)}`,at:Date.now(),name,target:clean(spec.target)||`generated/${name}.mjs`,source,reason:clean(spec.reason)||'requested capability synthesis',tests:Array.isArray(spec.tests)?spec.tests:[],modules:Object.freeze([...(spec.modules||[])])};this.history.push({...rec,sourceHash:hash(source),source:undefined});return rec;}
  synthesizeModule({name,contract={},address=null,dependencies=[],operations=[]}={}){
    const className=ident(name||contract.name||'GeneratedModule');
    const methods=(operations.length?operations:['execute']).map(op=>ident(op));
    const depDecl=dependencies.map((d,i)=>`    this.dep${i} = dependencies[${JSON.stringify(d)}] ?? null;`).join('\n');
    const methodSource=methods.map(method=>`  async ${method}(input, context = {}) {\n    return { ok: true, module: ${JSON.stringify(className)}, operation: ${JSON.stringify(method)}, address: this.address, input, context };\n  }`).join('\n');
    const source=`/** Addressable sovereign module generated by ${this.name}. */\nexport class ${className} {\n  constructor({ address = ${JSON.stringify(address)}, dependencies = {} } = {}) {\n    this.address = address;\n${depDecl||'    this.dependencies = dependencies;'}\n  }\n${methodSource}\n}\nexport default ${className};\n`;
    return {id:`module:${hash(source).slice(0,16)}`,target:`generated/modules/${className}.mjs`,source,contract,address,dependencies:Object.freeze([...dependencies])};
  }
  synthesizeTests({modulePath,exportName,operations=['execute']}={}){
    const target=clean(modulePath); const name=ident(exportName||'GeneratedModule');
    const source=`import assert from 'node:assert/strict';\nimport { ${name} } from '../${target.replace(/^\.\//,'')}';\nconst unit=new ${name}();\n${operations.map(op=>`assert.equal(typeof unit.${ident(op)}, 'function');`).join('\n')}\nconsole.log(${JSON.stringify(name+' generated-module smoke passed')});\n`;
    return {target:`tests/generated-${name}.smoke.mjs`,source};
  }
  synthesizeChangeSet({goal,project=[],modules=[],changes=[],tests=[]}={}){
    const inspection=project?.files?project:this.inspectProject(project);
    const plan=this.planChange({goal,project:inspection,capabilities:modules.flatMap(m=>m.capabilities||[]),targetFiles:changes.map(c=>c.target).filter(Boolean)});
    const files=[];
    for(const change of changes){ if(change.source) files.push({path:change.target,source:String(change.source),operation:change.operation||'write'}); else files.push(this.synthesize(change)); }
    for(const test of tests) files.push({path:test.target,source:String(test.source),operation:'write-test'});
    if(files.length>this.maxFiles) throw new RangeError('change set exceeds maxFiles');
    const manifest={version:1,id:`changeset:${hash(JSON.stringify({goal,files:files.map(f=>[f.path,hash(f.source)])})).slice(0,16)}`,goal:clean(goal),planId:plan.id,files:Object.freeze(files.map(f=>Object.freeze({...f,sha256:hash(f.source)}))),modules:Object.freeze(modules),requiresVerification:true};
    this.history.push({id:manifest.id,at:Date.now(),goal:manifest.goal,fileCount:files.length});
    return Object.freeze(manifest);
  }
  repair({target,source,problem,replacement}={}){if(!clean(target)||typeof source!=='string')throw new TypeError('target and source required');if(!replacement||typeof replacement.find!=='string')throw new TypeError('repair requires replacement.find');const next=source.replace(replacement.find,String(replacement.with??''));if(next===source)throw new Error('repair pattern not found');return {id:`repair:${hash(target+next).slice(0,16)}`,at:Date.now(),target,source:next,reason:clean(problem)||'source repair',operation:'replace'};}
  snapshot(){return {name:this.name,history:[...this.history],limits:{maxFiles:this.maxFiles,maxSourceBytes:this.maxSourceBytes}};}
}
export default AutoCoder;
