let _NodeWorker = null;
async function getWorkerCtor(){
  if (_NodeWorker) return _NodeWorker;
  if (typeof process === 'undefined' || !process?.versions?.node) return null;
  const mod = await import('node:worker_threads');
  _NodeWorker = mod.Worker;
  return _NodeWorker;
}


const EVIDENCE_WEIGHT=Object.freeze({
  dataflow:1.0,
  dependency:0.9,
  shared_state:0.8,
  ordered_sequence:0.45,
  cooccurrence:0.12,
  success_correlation:0.35,
  failure_correlation:-0.55,
  interference:-0.75,
  contradiction:-1.0
});
const stableMembers=members=>[...new Set(members.map(String))].sort();
const clean=s=>String(s??'').replace(/[^a-zA-Z0-9_.:-]+/g,'_').slice(0,120)||'global';
const processTypeIdFor=members=>`process-type:${stableMembers(members).join('+')}`;
const relationIdFor=(a,b,scope)=>`relation:${[String(a),String(b)].sort().join('<->')}@${clean(scope)}`;

export class ProcessFabric {
  constructor({supportThreshold=.72,minSessions=2,halfLifeObservations=96}={}){
    this.supportThreshold=Math.max(.2,Math.min(1,Number(supportThreshold)||.72));
    this.minSessions=Math.max(2,Number(minSessions)||2);
    this.halfLifeObservations=Math.max(12,Number(halfLifeObservations)||96);
    this.catalog=new Map();this.processes=new Map();this.processTypes=new Map();this.capabilityProcesses=new Map();
    this.workers=new Map();this.pending=new Map();this.entities=new Map();this.sessionTools=new Map();this.sessionOrder=new Map();
    this.relations=new Map();this.events=[];this.sequence=0;this.instanceSequence=0;
  }
  #uid(prefix){return `${prefix}:${String(++this.sequence).padStart(8,'0')}`;}
  #put(entity){const frozen=Object.freeze({...entity});this.entities.set(entity.id,frozen);return frozen;}
  #recordCapability(d){return this.#put({id:`capability:${d.id}`,kind:'capability',scale:'primitive',toolId:d.id,name:d.name,provides:[...(d.provides||[])],origin:{type:'supplied-runtime',source:'PASS6-tool-registry'},parents:[]});}
  boot(toolDescriptors=[]){for(const d of toolDescriptors){if(this.catalog.has(d.id))continue;this.catalog.set(d.id,{...d,provides:[...(d.provides||[])]});this.#recordCapability(d);}return this;}
  registerExternalProcess({id,kind='process',role='external',members=[],origin={},parents=[]}={}){if(!id)throw new Error('external process requires id');const rec={id,kind,scale:'process',role,members:[...members],origin:{...origin},parents:[...parents],status:'active',formationReason:'explicit runtime role with independent state/lifecycle'};this.processes.set(id,rec);return this.#put(rec);}
  #sessionKey(context={}){return String(context?.sessionId||context?.inputValues?.intentRecord?.executionContext?.runId||context?.inputValues?.intentRecord?.intentId||'session:unresolved');}
  #lane(context={}){return context?.inputValues?.intentRecord?.executionContext?.lane||null;}
  #scope(context={}){const lane=this.#lane(context)||'unscoped';const caps=[...(context?.expression?.capabilities||[])].sort().slice(0,6).join(',')||'general';return `${lane}|${caps}`;}
  #decay(seq){const age=Math.max(0,this.sequence-seq);return 2**(-age/this.halfLifeObservations);}
  #scoreRelation(r){let positive=0,negative=0;for(const e of r.evidence){const w=(EVIDENCE_WEIGHT[e.type]??0)*this.#decay(e.sequence);if(w>=0)positive+=w;else negative+=-w;}const total=positive+negative+0.25;const confidence=Math.max(0,Math.min(1,positive/total));const support=Math.max(-1,Math.min(1,(positive-negative)/Math.max(1,r.sessions.size)));return {positive,negative,confidence,support};}
  #syncRelationEntity(r){const score=this.#scoreRelation(r);const sequenceEvidence=r.evidence.filter(e=>e.type==='ordered_sequence'||e.type==='dataflow'||e.type==='dependency').length;const status=r.sessions.size>=this.minSessions&&score.confidence>=this.supportThreshold&&sequenceEvidence>=this.minSessions?'supported':score.negative>score.positive?'contradicted':'provisional';Object.assign(r,score,{status,sequenceEvidence});this.#put({id:r.id,kind:'hypothesis',scale:'relation',members:[...r.members],contextScope:r.contextScope,support:r.support,confidence:r.confidence,positiveEvidence:r.positive,negativeEvidence:r.negative,observedSessions:r.sessions.size,evidence:r.evidence.map(e=>e.id),status:r.status,parents:r.members.map(x=>`capability:${x}`)});return r;}
  #recordRelationEvidence(a,b,context,{type='cooccurrence',evidenceId=null,details={}}={}){if(a===b)return null;const scope=this.#scope(context);const id=relationIdFor(a,b,scope);let r=this.relations.get(id);if(!r)r={id,kind:'hypothesis',scale:'relation',members:stableMembers([a,b]),contextScope:scope,sessions:new Set(),evidence:[],status:'provisional'};const sessionId=this.#sessionKey(context);r.sessions.add(sessionId);const ev=this.#put({id:evidenceId||this.#uid('evidence'),kind:'evidence',scale:'primitive',evidenceType:type,weight:EVIDENCE_WEIGHT[type]??0,sessionId,contextScope:scope,details:{...details},origin:{type:'runtime-observation'},parents:[`capability:${a}`,`capability:${b}`]});r.evidence.push({id:ev.id,type,sequence:this.sequence,sessionId});this.relations.set(id,r);return this.#syncRelationEntity(r);}
  recordRelationEvidence(a,b,context={},evidence={}){if(!this.catalog.has(a)||!this.catalog.has(b))throw new Error('relation evidence requires known capabilities');const r=this.#recordRelationEvidence(a,b,context,evidence);this.#promoteSupportedRelations();return r;}
  #observe(toolId,context){const sessionId=this.#sessionKey(context);const order=this.sessionOrder.get(sessionId)||[];const previous=order.at(-1)||null;const obs=this.#put({id:this.#uid('observation'),kind:'observation',scale:'primitive',toolId,sessionId,lane:this.#lane(context),contextScope:this.#scope(context),expressionCapabilities:[...(context?.expression?.capabilities||[])],origin:{type:'runtime-execution',sessionId},parents:[`capability:${toolId}`]});if(!this.sessionTools.has(sessionId))this.sessionTools.set(sessionId,new Set());for(const peer of this.sessionTools.get(sessionId))if(peer!==toolId)this.#recordRelationEvidence(peer,toolId,context,{type:'cooccurrence',evidenceId:obs.id,details:{reason:'same execution session'}});if(previous&&previous!==toolId)this.#recordRelationEvidence(previous,toolId,context,{type:'ordered_sequence',details:{order:[previous,toolId]}});this.sessionTools.get(sessionId).add(toolId);order.push(toolId);this.sessionOrder.set(sessionId,order);return obs;}
  #createProcessType(rel){const id=`${processTypeIdFor(rel.members)}@${clean(rel.contextScope)}`;let t=this.processTypes.get(id);if(t)return t;t={id,kind:'process-type',scale:'pattern',members:[...rel.members],contextScope:rel.contextScope,status:'supported-pattern',evidence:[rel.id,...rel.evidence.map(e=>e.id)],origin:{type:'observed-process-pattern'},parents:[rel.id,...rel.members.map(m=>`capability:${m}`)]};this.processTypes.set(id,t);this.#put(t);return t;}
  #createProcessInstance(rel){const existing=[...this.processes.values()].find(p=>p.typeId&&p.typeId===`${processTypeIdFor(rel.members)}@${clean(rel.contextScope)}`&&p.status==='selected');if(existing)return existing;const type=this.#createProcessType(rel);const id=`process:${String(++this.instanceSequence).padStart(6,'0')}:${rel.members.join('+')}`;const alternatives=[{structure:'independent',members:[...rel.members]},{structure:'ordered',members:[...rel.members]},{structure:'shared-process',members:[...rel.members]}];const experiment={id:this.#uid('experiment'),kind:'structural-experiment',alternatives,selected:'shared-process',basis:{sessions:rel.sessions.size,confidence:rel.confidence,support:rel.support,sequenceEvidence:rel.sequenceEvidence},parents:[rel.id]};this.#put(experiment);const rec={id,typeId:type.id,kind:'process',scale:'process',members:[...rel.members],status:'selected',contextScope:rel.contextScope,formationReason:'selected after recurrent contextual evidence and structural comparison',evidence:[rel.id,...rel.evidence.map(e=>e.id),experiment.id],origin:{type:'emergent-process-fabric'},parents:[type.id,rel.id,experiment.id,...rel.members.map(m=>`capability:${m}`)],selectedStructure:{kind:'shared-process',members:[...rel.members]},alternatives};this.processes.set(id,rec);for(const m of rec.members){if(!this.capabilityProcesses.has(m))this.capabilityProcesses.set(m,new Set());this.capabilityProcesses.get(m).add(id);}this.#put(rec);return rec;}
  #promoteSupportedRelations(){for(const rel of this.relations.values()){this.#syncRelationEntity(rel);if(rel.status!=='supported')continue;const causal=rel.evidence.filter(e=>['dataflow','dependency','shared_state'].includes(e.type)).length;const matureSequence=rel.sessions.size>=4&&rel.sequenceEvidence>=4;if(causal>0||matureSequence)this.#createProcessInstance(rel);}}
  #candidateProcesses(toolId,context){const ids=[...(this.capabilityProcesses.get(toolId)||[])];const scope=this.#scope(context);return ids.map(id=>this.processes.get(id)).filter(Boolean).filter(p=>p.status==='selected'&&p.contextScope===scope).sort((a,b)=>b.members.length-a.members.length);}
  #ensureSingleton(toolId,obs,context){const scope=this.#scope(context);const existing=[...this.processes.values()].find(p=>p.members?.length===1&&p.members[0]===toolId&&p.contextScope===scope&&p.status==='selected');if(existing)return existing;const id=`process:${String(++this.instanceSequence).padStart(6,'0')}:${toolId}`;const rec={id,typeId:`${processTypeIdFor([toolId])}@${clean(scope)}`,kind:'process',scale:'process',members:[toolId],status:'selected',contextScope:scope,formationReason:'independently executable capability observed in context',evidence:[obs.id],origin:{type:'emergent-process-fabric'},parents:[obs.id,`capability:${toolId}`],selectedStructure:{kind:'singleton',members:[toolId]}};this.processes.set(id,rec);if(!this.capabilityProcesses.has(toolId))this.capabilityProcesses.set(toolId,new Set());this.capabilityProcesses.get(toolId).add(id);this.#put(rec);return rec;}
  async #spawnProcess(process){if(this.workers.get(process.id)?.ready)return this.workers.get(process.id);const Worker=await getWorkerCtor();if(!Worker)throw new Error('Process worker execution requires the Node residence host; browser residence keeps process evidence/lineage but does not spawn Node worker_threads.');return new Promise((resolve,reject)=>{const worker=new Worker(new URL('./process_worker.mjs',import.meta.url),{workerData:{processId:process.id,members:process.members}});const rec={worker,ready:false,snapshot:null};this.workers.set(process.id,rec);worker.on('message',msg=>{this.events.push({sequence:this.events.length+1,...msg});if(msg.type==='ready'){rec.ready=true;rec.snapshot=msg.snapshot;return resolve(rec);}if(msg.id&&this.pending.has(msg.id)){const p=this.pending.get(msg.id);this.pending.delete(msg.id);msg.type==='error'?p.reject(new Error(msg.error)):p.resolve(msg.result);}});worker.on('error',reject);worker.on('exit',code=>{rec.ready=false;if(code!==0)this.events.push({type:'process-worker-exit',processId:process.id,code});});});}
  async execute(toolId,context={}){if(!this.catalog.has(toolId))throw new Error(`Unknown capability: ${toolId}`);const obs=this.#observe(toolId,context);this.#promoteSupportedRelations();const candidates=this.#candidateProcesses(toolId,context);const process=candidates.find(p=>p.members.length>1)||candidates.find(p=>p.members.length===1)||this.#ensureSingleton(toolId,obs,context);const rec=await this.#spawnProcess(process);const id=this.#uid('execution');const started=performance.now();try{const result=await new Promise((resolve,reject)=>{this.pending.set(id,{resolve,reject});rec.worker.postMessage({type:'execute',id,toolId,context});});const durationMs=performance.now()-started;const resultEntity=this.#put({id:this.#uid('result'),kind:'result',scale:'primitive',toolId,processId:process.id,sessionId:this.#sessionKey(context),summary:{success:result?.success!==false,durationMs},origin:{type:'process-execution'},parents:[obs.id,process.id]});if(process.members.length>1)for(const peer of process.members)if(peer!==toolId)this.#recordRelationEvidence(peer,toolId,context,{type:'success_correlation',details:{processId:process.id,durationMs}});this.#put({id:this.#uid('transition'),kind:'transition',scale:'primitive',operator:'execute',from:obs.id,to:resultEntity.id,processId:process.id,parents:[obs.id,process.id,resultEntity.id]});this.#promoteSupportedRelations();return {...result,trace:{processId:process.id,processTypeId:process.typeId,observationId:obs.id,resultId:resultEntity.id,lineage:this.why(resultEntity.id)}};}catch(error){for(const peer of process.members)if(peer!==toolId)this.#recordRelationEvidence(peer,toolId,context,{type:'failure_correlation',details:{processId:process.id,error:String(error)}});throw error;}}
  compose(memberIds=[],{reason='explicit recursive composition',evidence=[],status='provisional'}={}){const members=[...new Set(memberIds.map(String))].sort();if(members.length<2)throw new Error('recursive composition requires at least two members');for(const id of members)if(!this.entities.has(id)&&!this.processes.has(id))throw new Error(`Unknown composition member: ${id}`);const id=`process-of:${String(++this.instanceSequence).padStart(6,'0')}:${members.join('+')}`;const rec={id,typeId:`process-type-of:${members.join('+')}`,kind:'process',scale:'recursive-process',members,status,formationReason:reason,evidence:[...evidence],origin:{type:'recursive-composition'},parents:[...new Set([...evidence,...members])],selectedStructure:{kind:'recursive',members}};this.processes.set(id,rec);this.#put(rec);return rec;}
  project(id,scale='interaction'){const source=this.entities.get(id)||this.processes.get(id);if(!source)return null;const projectionId=`projection:${scale}:${id}`;let presentation;if(source.kind==='hypothesis')presentation={type:'hypothesis',question:`Do ${source.members?.join(' and ')} form a stable relationship in ${source.contextScope}?`,confidence:source.confidence,support:source.support,status:source.status,evidence:[...(source.evidence||[])]};else if(source.kind==='process')presentation={type:'process',members:[...(source.members||[])],status:source.status,reason:source.formationReason||null,contextScope:source.contextScope||null};else presentation={type:source.kind,summary:{...source}};return this.#put({id:projectionId,kind:'projection',scale,semanticId:id,presentation,origin:{type:'scale-projection'},parents:[id]});}
  hypothesisStatus(){return [...this.relations.values()].map(r=>({id:r.id,members:[...r.members],contextScope:r.contextScope,status:r.status,support:r.support,confidence:r.confidence,observedSessions:r.sessions.size,sequenceEvidence:r.sequenceEvidence,evidence:r.evidence.map(e=>e.id)}));}
  processStatus(){return [...this.processes.values()].map(p=>({...p,workerReady:Boolean(this.workers.get(p.id)?.ready)}));}
  inspect(id){return this.entities.get(id)||this.processes.get(id)||null;}
  why(id,{maxDepth=12}={}){const seen=new Set();const walk=(x,depth)=>{if(depth>maxDepth||seen.has(x))return {id:x,truncated:true};seen.add(x);const e=this.entities.get(x)||this.processes.get(x);if(!e)return {id:x,missing:true};return {id:e.id,kind:e.kind,scale:e.scale,status:e.status||null,origin:e.origin||null,reason:e.formationReason||e.reason||null,contextScope:e.contextScope||null,parents:(e.parents||[]).map(p=>walk(p,depth+1))};};return walk(id,0);}
  whyNot(relationId){const r=this.relations.get(relationId);if(!r)return null;return {id:r.id,status:r.status,confidence:r.confidence,support:r.support,blocking:{needsSessions:Math.max(0,this.minSessions-r.sessions.size),needsConfidence:Math.max(0,this.supportThreshold-r.confidence),contradictions:r.evidence.filter(e=>(EVIDENCE_WEIGHT[e.type]??0)<0).map(e=>e.id)},alternatives:['remain-independent','ordered-pipeline','shared-process']};}
  counterfactual(processId,{without=[]}={}){const p=this.processes.get(processId);if(!p)return null;const omit=new Set((Array.isArray(without)?without:[without]).map(String));const remaining=p.members.filter(m=>!omit.has(m));return {processId,originalMembers:[...p.members],without:[...omit],counterfactualMembers:remaining,executable:remaining.length>0,note:'structural counterfactual; execution requires an explicit replay request with original inputs',parents:[processId]};}
  status(){return {capabilities:this.catalog.size,liveProcessWorkers:[...this.workers.values()].filter(r=>r.ready).length,selectedProcesses:this.processStatus().filter(p=>p.status==='selected').length,processTypes:this.processTypes.size,processes:this.processStatus(),hypotheses:this.hypothesisStatus(),entities:this.entities.size,events:this.events.length,pending:this.pending.size,physics:{supportThreshold:this.supportThreshold,minSessions:this.minSessions,halfLifeObservations:this.halfLifeObservations,evidenceWeights:EVIDENCE_WEIGHT}};}
  async close(){await Promise.all([...this.workers.values()].map(({worker})=>worker.terminate()));this.workers.clear();}
}
export default ProcessFabric;
