// Deterministic AUTOLING-inspired interaction learner.
// Learns grammar from successful/failed interaction and stores it in the 5D mesh.
const FIVE=['Movement','Evolution','Being','Design','Space'];
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const gateFor=s=>(hash(s)%64)+1;
const tokenize=s=>(String(s).toLowerCase().match(/[a-z0-9][a-z0-9'_-]*/g)||[]);
const fields=(roles=[])=>{const f={Movement:1,Evolution:1,Being:1,Design:1,Space:1},map={what:'Movement',when:'Evolution',where:'Being',why:'Design',who:'Space'};for(const r of roles)f[map[r]||'Being']+=1;return f};
function inferRoles(text){const x=String(text),roles=[];if(/\b(i|you|we|they|he|she|who|user|agent)\b/i.test(x))roles.push('who');if(/\b(do|make|build|create|open|read|write|run|install|fix|generate|what)\b/i.test(x))roles.push('what');if(/\b(where|here|there|inside|on|at|from|to)\b/i.test(x))roles.push('where');if(/\b(when|today|tomorrow|before|after|now|later)\b/i.test(x))roles.push('when');if(/\b(why|because|so that|purpose|goal|need)\b/i.test(x))roles.push('why');return [...new Set(roles.length?roles:['what'])]}
function pattern(tokens){return tokens.map(t=>/^\d+$/.test(t)?'<number>':t.length>16?'<long>':t).slice(0,48).join(' ')}
export class KleinAutoLingLearner{
  constructor(mesh,{failureWindow=6,maxRecycles=3}={}){this.mesh=mesh;this.failureWindow=failureWindow;this.maxRecycles=maxRecycles;this.history=[];this.recycleCount=0}
  observe(utterance,{success=null,context={},outcome=null}={}){
    const words=tokenize(utterance),roles=inferRoles(utterance),form=pattern(words),key=`${form}|${roles.join(',')}`,gate=gateFor(key),dimension=roles.includes('why')?'Design':roles.includes('who')?'Space':roles.includes('when')?'Evolution':roles.includes('where')?'Being':'Movement';
    const event={utterance:String(utterance),words,roles,form,success:success===null?null:Boolean(success),outcome,timestamp:Date.now()};this.history.push(event);if(this.history.length>128)this.history.shift();
    const id=`autoling:${hash(key).toString(16)}`;let node=this.mesh.node(id);
    if(success!==false){if(!node){node=this.mesh.addState({id,kind:'learned-grammar',scale:'linguistic',text:form,fields:fields(roles),address:{dimension,gate,canonicalAddressStatus:'learned-derived'},source:{type:'klein-autoling'},residency:'warm',provenance:[],attributes:{epistemicStatus:'derived',roles,form,successCount:0,failureCount:0,examples:[]}})}node.attributes.successCount=(node.attributes.successCount||0)+(success===true?1:0);node.attributes.examples=[...(node.attributes.examples||[]),String(utterance)].slice(-8)}
    if(success===false){if(!node){node=this.mesh.addState({id,kind:'learned-grammar',scale:'linguistic',text:form,fields:fields(roles),address:{dimension,gate,canonicalAddressStatus:'learned-derived'},source:{type:'klein-autoling'},residency:'warm',provenance:[],attributes:{epistemicStatus:'derived',roles,form,successCount:0,failureCount:0,examples:[]}})}node.attributes.failureCount=(node.attributes.failureCount||0)+1;const failId=`illegal:${hash(`${key}:${this.history.length}`).toString(16)}`;this.mesh.addState({id:failId,kind:'grammar-rejection',scale:'linguistic',text:String(utterance),fields:fields(roles),address:{dimension,gate,canonicalAddressStatus:'observed-rejection'},source:{type:'klein-autoling'},residency:'cold',provenance:[id],attributes:{epistemicStatus:'recorded',context,outcome}});this.mesh.addEdge({from:failId,to:id,type:'rejects-pattern',status:'recorded',evidence:[failId],dedupe:true});this.recycleIfNeeded()}
    return {id,roles,form,dimension,gate,success};
  }
  recycleIfNeeded(){const recent=this.history.slice(-this.failureWindow).filter(x=>x.success!==null);if(recent.length<this.failureWindow)return null;const failures=recent.filter(x=>x.success===false).length;if(failures/this.failureWindow<0.67||this.recycleCount>=this.maxRecycles)return null;this.recycleCount++;const weak=[...this.mesh.nodes.values()].filter(n=>n.kind==='learned-grammar'&&(n.attributes?.failureCount||0)>(n.attributes?.successCount||0));for(const n of weak)this.mesh.setResidency(n.id,'cold');const id=`grammar-recycle:${this.recycleCount}:${Date.now()}`;this.mesh.addState({id,kind:'grammar-recycle',scale:'learning',text:`AUTOLING recycle ${this.recycleCount}`,fields:{Movement:1,Evolution:3,Being:1,Design:2,Space:1},address:{dimension:'Evolution',gate:gateFor(id),canonicalAddressStatus:'derived'},source:{type:'klein-autoling'},residency:'warm',provenance:weak.map(n=>n.id),attributes:{epistemicStatus:'derived',cooledPatterns:weak.map(n=>n.id)}});return id}
  analyze(utterance){const words=tokenize(utterance),roles=inferRoles(utterance),form=pattern(words);const key=`${form}|${roles.join(',')}`,id=`autoling:${hash(key).toString(16)}`,known=this.mesh.node(id);return {words,roles,form,knownRule:known?{id,successCount:known.attributes?.successCount||0,failureCount:known.attributes?.failureCount||0}:null}}
}
export default KleinAutoLingLearner;
