const clamp=(n,min=0,max=1)=>Math.max(min,Math.min(max,Number(n)||0));
const clone=x=>structuredClone(x);
const DIMS=Object.freeze(['Space','Evolution','Being','Movement','Design']);
export const INTERROGATIVES=Object.freeze({Space:'Who',Evolution:'What',Being:'Where',Movement:'When',Design:'Why'});

const mean=a=>a.length?a.reduce((s,n)=>s+n,0)/a.length:0;
const signature=v=>v.reduce((s,b,i)=>s+(b?2**(i%6):0),0);

/**
 * One enduring gate process. It is not a row regenerated by GateProcessField.
 * It retains its own observations, dimensional state and local history.
 * The five dimensions do not share one evaluator: each keeps its own concern,
 * evidence and choice while remaining part of this one gate process.
 */
export class GateLocus{
  constructor({gate,kernel,saved=null}={}){
    if(!Number.isInteger(gate)||gate<1||gate>64)throw new RangeError('gate 1..64 required');
    this.gate=gate;this.kernel=kernel;
    this.address={mode:'macro',gate,line:1,color:1,tone:1,base:1};
    this.vector=[...kernel.vector(this.address)];
    this.structuralSignature=signature(this.vector);
    this.observations=Number(saved?.observations||0);
    this.lastSeenAt=Number(saved?.lastSeenAt||0)||null;
    this.lastInputKey=saved?.lastInputKey||null;
    this.history=Array.isArray(saved?.history)?saved.history.slice(-24):[];
    this.dimensions={};
    for(const d of DIMS)this.dimensions[d]=saved?.dimensions?.[d]||this.#empty(d);
  }

  observe(ctx={}){
    const now=Number(ctx.now||Date.now());
    const previousKey=this.lastInputKey;
    const changed=Boolean(previousKey&&previousKey!==ctx.inputKey);
    const isAddressed=this.gate===Number(ctx.activeGate||0);
    const localStructure=this.#structure();
    const next={
      Space:this.#space(ctx,{isAddressed,localStructure}),
      Evolution:this.#evolution(ctx,{isAddressed,localStructure,changed}),
      Being:this.#being(ctx,{isAddressed,localStructure}),
      Movement:this.#movement(ctx,{isAddressed,localStructure,changed,now}),
      Design:this.#design(ctx,{isAddressed,localStructure})
    };
    this.observations++;this.lastSeenAt=now;this.lastInputKey=ctx.inputKey;
    for(const d of DIMS){
      const prior=this.dimensions[d];
      const value={...next[d],dimension:d,question:INTERROGATIVES[d],gate:this.gate,previousChoice:prior?.choice||null,changedChoice:Boolean(prior?.choice&&prior.choice!==next[d].choice),observedAt:now};
      this.dimensions[d]=value;
    }
    const activity=Math.max(...DIMS.map(d=>this.dimensions[d].activation));
    const record={at:now,inputKey:ctx.inputKey,activity,choices:Object.fromEntries(DIMS.map(d=>[d,this.dimensions[d].choice]))};
    this.history.push(record);if(this.history.length>24)this.history.shift();
    return this.snapshot({activity,isAddressed});
  }

  meet(other,{at=Date.now(),reason='co-active',leftElement=null,rightElement=null}={}){
    const a=this.snapshot(),b=other.snapshot();
    const overlap=DIMS.filter(d=>a.decisions[d].activation>.45&&b.decisions[d].activation>.45);
    const tension=DIMS.filter(d=>a.decisions[d].choice!==b.decisions[d].choice&&a.decisions[d].activation>.5&&b.decisions[d].activation>.5);
    const strength=clamp((overlap.length/5)*.7+((a.activity+b.activity)/2)*.3);
    return {
      id:`G${Math.min(this.gate,other.gate)}:G${Math.max(this.gate,other.gate)}`,
      kind:'subjective-relation-field',
      participants:[this.gate,other.gate],reason,at,strength,overlap,tension,
      // A relation does not erase either participant. Elements remain theirs.
      elemental:{[this.gate]:leftElement,[other.gate]:rightElement},
      objectivities:{[this.gate]:{signature:this.structuralSignature},[other.gate]:{signature:other.structuralSignature}}
    };
  }

  snapshot(extra={}){
    const decisions=Object.fromEntries(DIMS.map(d=>[d,clone(this.dimensions[d])]));
    const activity=extra.activity??Math.max(...DIMS.map(d=>Number(decisions[d]?.activation||0)));
    return {gate:this.gate,address:{...this.address},vector:[...this.vector],structuralSignature:this.structuralSignature,observations:this.observations,lastSeenAt:this.lastSeenAt,decisions,activity,active:Boolean(extra.isAddressed),history:this.history.slice(-8).map(clone)};
  }

  serialize(){return {gate:this.gate,observations:this.observations,lastSeenAt:this.lastSeenAt,lastInputKey:this.lastInputKey,dimensions:clone(this.dimensions),history:this.history.slice(-24).map(clone)};}

  #empty(d){return {dimension:d,question:INTERROGATIVES[d],activation:0,choice:'quiet',evidence:{},observedAt:null};}
  #structure(){
    const chunks=[0,1,2,3,4].map(i=>mean(this.vector.filter((_,j)=>j%5===i)));
    return {Space:chunks[0],Evolution:chunks[1],Being:chunks[2],Movement:chunks[3],Design:chunks[4]};
  }
  #choice(activation,choices){return activation>.76?choices[3]:activation>.55?choices[2]:activation>.32?choices[1]:choices[0];}

  #space(ctx,{isAddressed,localStructure}){
    const participants=ctx.participants||[];
    const relationPressure=clamp((participants.length-1)/6);
    const activation=clamp(localStructure.Space*.38+relationPressure*.34+(isAddressed?.22:0)+(ctx.relationCarry||0)*.06);
    const choice=this.#choice(activation,['remain-self','notice-other','relate','negotiate-relation']);
    return {activation,choice,concern:'who / relation / subjective field',evidence:{participants:[...participants],relationPressure,isAddressed,rule:'relation may form between objectivities; neither participant is replaced by the relation'}};
  }
  #evolution(ctx,{isAddressed,localStructure,changed}){
    const adaptation=clamp(ctx.adaptation||0),repair=clamp(ctx.repair||0);
    const activation=clamp(localStructure.Evolution*.34+(changed?.24:0)+adaptation*.25+repair*.11+(isAddressed?.06:0));
    const choice=this.#choice(activation,['retain','notice-change','adapt','transform']);
    return {activation,choice,concern:'what / state / change',evidence:{changed,adaptation,repair,isAddressed,inputKey:ctx.inputKey}};
  }
  #being(ctx,{isAddressed,localStructure}){
    const vitality=clamp(ctx.vitality??.68),located=Boolean(ctx.whereKnown||ctx.addressKnown);
    const activation=clamp(localStructure.Being*.30+vitality*.30+(located?.24:0)+(isAddressed?.16:0));
    const choice=this.#choice(activation,['hold-condition','sense-condition','inhabit','assert-condition']);
    return {activation,choice,concern:'where / situated condition',evidence:{vitality,where:ctx.where||null,addressKnown:Boolean(ctx.addressKnown),isAddressed}};
  }
  #movement(ctx,{isAddressed,localStructure,changed,now}){
    const elapsed=this.lastSeenAt?Math.min(1,(now-this.lastSeenAt)/Math.max(1,ctx.intervalMs||5000)):0;
    const timingKnown=Boolean(ctx.whenKnown),pulsePhase=((Number(ctx.pulses||0)%6)+1)/6;
    const activation=clamp(localStructure.Movement*.28+elapsed*.20+pulsePhase*.18+(timingKnown?.18:0)+(changed?.10:0)+(isAddressed?.06:0));
    const choice=this.#choice(activation,['wait','prepare','move','transition']);
    return {activation,choice,concern:'when / sequence / transition',evidence:{elapsed,pulses:Number(ctx.pulses||0),when:ctx.when||null,changed,isAddressed}};
  }
  #design(ctx,{isAddressed,localStructure}){
    const purposeKnown=Boolean(ctx.whyKnown||ctx.purpose),intentPresent=Boolean(ctx.intent);
    const unresolvedPurpose=intentPresent&&!purposeKnown;
    const activation=clamp(localStructure.Design*.30+(purposeKnown?.34:0)+(unresolvedPurpose?.24:0)+(isAddressed?.12:0));
    const choice=unresolvedPurpose?'question-purpose':this.#choice(activation,['hold-form','consider-form','form-from-purpose','integrate-purpose']);
    return {activation,choice,concern:'why / purpose / formative reason',evidence:{purpose:ctx.purpose||null,why:ctx.why||null,unresolvedPurpose,isAddressed}};
  }
}
export default GateLocus;
