/**
 * SuccessMetabolism
 * Verified user progress replenishes adaptation capacity. Mere execution does
 * not. Maintenance and real work consume vitality, so the organism develops
 * endogenous pressure even when nobody calls a "grow" method.
 */
const clamp=(n,min=0,max=1)=>Math.max(min,Math.min(max,n));
const slope=values=>{if(values.length<2)return 0;const n=values.length,sx=(n-1)*n/2,sy=values.reduce((a,b)=>a+b,0),sxy=values.reduce((a,y,x)=>a+x*y,0),sx2=values.reduce((a,_,x)=>a+x*x,0),d=n*sx2-sx*sx;return d===0?0:(n*sxy-sx*sy)/d;};
export class SuccessMetabolism {
  constructor({residence=null,purpose='User-defined success',indicators=[],maintenancePerMinute=.003}={}){this.residence=structuredClone(residence);this.purpose=purpose;this.indicators=new Map();this.events=[];this.vitality=.68;this.adaptationBudget=0;this.repairPressure=0;this.sequence=0;this.maintenancePerMinute=Math.max(0,Number(maintenancePerMinute)||0);this.totalSpent=0;this.totalReplenished=0;for(const i of indicators)this.defineIndicator(i);}
  defineIndicator({id,name=id,direction='increase',weight=1}={}){if(!id)throw new Error('indicator id required');if(!['increase','decrease','maintain'].includes(direction))throw new Error('direction must be increase|decrease|maintain');const rec={id:String(id),name:String(name),direction,weight:Number(weight)||1,observations:[]};this.indicators.set(rec.id,rec);return this.progress(rec.id);}
  observe(indicatorId,value,{evidence,source='user',context=null}={}){const i=this.indicators.get(indicatorId);if(!i)throw new Error(`unknown success indicator ${indicatorId}`);if(!Number.isFinite(Number(value)))throw new Error('success observation must be numeric');if(!evidence||typeof evidence!=='object')throw new Error('verified user-success evidence is required');const before=this.progress(indicatorId),o={sequence:++this.sequence,value:Number(value),evidence:structuredClone(evidence),source,context,at:Date.now()};i.observations.push(o);const after=this.progress(indicatorId),delta=this.#towardDelta(i,before,after);if(delta>0){const fuel=delta*i.weight;this.vitality=clamp(this.vitality+Math.min(.14,fuel*.065));this.adaptationBudget+=fuel;this.totalReplenished+=fuel;this.repairPressure=clamp(this.repairPressure-Math.min(.15,fuel*.03));}else if(after.evidenceCount>=2&&after.direction==='away'){this.repairPressure=clamp(this.repairPressure+Math.min(.2,Math.abs(after.signedRate)*.04+.02));}
    const event={type:delta>0?'user-progress':'user-feedback',indicatorId,delta,before,after,evidence:o.evidence,sequence:o.sequence,at:o.at};this.events.push(event);return event;}
  #towardDelta(i,before,after){if(after.evidenceCount<2)return 0;const a=after.signedRate,b=before.signedRate||0;if(i.direction==='increase')return Math.max(0,a)-Math.max(0,b);if(i.direction==='decrease')return Math.max(0,-a)-Math.max(0,-b);return Math.max(0,Math.abs(b)-Math.abs(a));}
  progress(id){const i=this.indicators.get(id);if(!i)return null;const values=i.observations.slice(-5).map(x=>x.value),r=slope(values);let direction='unknown';if(values.length>=2){if(i.direction==='increase')direction=r>0?'toward':r<0?'away':'neutral';if(i.direction==='decrease')direction=r<0?'toward':r>0?'away':'neutral';if(i.direction==='maintain')direction=Math.abs(r)<=.1?'toward':'away';}return {id:i.id,name:i.name,direction,goalDirection:i.direction,signedRate:r,rate:Math.abs(r),values:[...values],evidenceCount:i.observations.length};}
  tick({dtMs=1000,activeProcesses=0,memoryLoad=0,unresolvedNeeds=0}={}){const minutes=Math.max(0,Number(dtMs)||0)/60000;const maintenance=this.maintenancePerMinute*minutes;const processCost=Math.max(0,Number(activeProcesses)||0)*.00008*minutes;const memoryCost=Math.log1p(Math.max(0,Number(memoryLoad)||0))*.000015*minutes;const needCost=Math.min(.002,Math.max(0,Number(unresolvedNeeds)||0)*.00003)*minutes;const cost=maintenance+processCost+memoryCost+needCost;this.vitality=clamp(this.vitality-cost);if(this.vitality<.35)this.repairPressure=clamp(this.repairPressure+(.35-this.vitality)*.01);const event={type:'metabolic-tick',dtMs,maintenance,processCost,memoryCost,needCost,cost,vitality:this.vitality,repairPressure:this.repairPressure,at:Date.now()};this.events.push(event);return event;}
  registerWork({cost=.002,kind='work',evidence=null,failed=false}={}){const n=Math.max(0,Number(cost)||0);this.vitality=clamp(this.vitality-n);this.totalSpent+=n;if(failed)this.repairPressure=clamp(this.repairPressure+Math.max(.02,n*3));const e={type:failed?'work-failure':'work-cost',kind,cost:n,vitality:this.vitality,repairPressure:this.repairPressure,evidence:structuredClone(evidence),at:Date.now()};this.events.push(e);return e;}
  consumeAdaptation(amount=1,{reason='adaptation',evidence=null}={}){const requested=Math.max(0,Number(amount)||0),n=Math.min(this.adaptationBudget,requested);this.adaptationBudget-=n;this.totalSpent+=n;const e={type:'adaptation-spent',requested,spent:n,reason,evidence:structuredClone(evidence),at:Date.now()};this.events.push(e);return e;}
  addRepairPressure(amount,{reason='feedback',evidence=null}={}){const n=Math.max(0,Number(amount)||0);this.repairPressure=clamp(this.repairPressure+n);const e={type:'repair-pressure',amount:n,reason,evidence:structuredClone(evidence),at:Date.now()};this.events.push(e);return e;}
  relieveRepairPressure(amount,{reason='repair'}={}){const n=Math.max(0,Number(amount)||0);this.repairPressure=clamp(this.repairPressure-n);this.events.push({type:'repair-relief',amount:n,reason,at:Date.now()});return this.repairPressure;}
  snapshot(){return {residence:structuredClone(this.residence),purpose:this.purpose,vitality:this.vitality,adaptationBudget:this.adaptationBudget,repairPressure:this.repairPressure,totalSpent:this.totalSpent,totalReplenished:this.totalReplenished,thriving:[...this.indicators].map(([id])=>this.progress(id)),events:this.events.slice(-128).map(x=>structuredClone(x))};}
}
export default SuccessMetabolism;
