import test from 'node:test';
import assert from 'node:assert/strict';
import {SymbolCompositionGraph} from '../components/organism/integration/SymbolCompositionGraph.mjs';
import {morphFrame,SwarmMorphView} from '../components/organism/browser/SwarmMorphView.mjs';
function fixture(){const graph=new SymbolCompositionGraph();for(let i=0;i<40;i++)graph.occurrence({id:`letter-${i}`,symbol:i===0?'<':String.fromCharCode(65+i%26),address:{gate:1,dimension:'Design'}});return {graph,node:graph.compose(Array.from({length:40},(_,i)=>`letter-${i}`))};}
test('the same graph identities and addresses survive every embodiment',()=>{const {graph,node}=fixture(),before=graph.snapshot();for(const form of ['text','chair','house','body','world','page']){const frame=morphFrame(node,{form});assert.equal(frame.length,40);assert.deepEqual(frame.map(p=>p.id),node.members.map(m=>m.member.id));assert.equal(frame[0].address.gate,1);}assert.deepEqual(graph.snapshot(),before);assert.notDeepEqual(morphFrame(node,{form:'chair'}).map(p=>p.x),morphFrame(node).map(p=>p.x));});
test('resolved holding strength deforms expression without removing connections',()=>{const {node}=fixture();const strong=morphFrame(node,{form:'house'}),weak=morphFrame(node,{form:'house',resolveState:()=>({holdingStrength:0,qualities:['continuity']})});assert.equal(weak.length,strong.length);assert.equal(weak[0].id,strong[0].id);assert.notEqual(weak[0].y,strong[0].y);assert.deepEqual(weak[0].state.qualities,['continuity']);});
test('nested shared membership retains identity and separate placements',()=>{const {graph,node}=fixture();const parent=graph.compose([node.id,node.id]);const frame=morphFrame(parent);assert.equal(frame.length,80);assert.equal(frame[0].id,frame[40].id);assert.notEqual(frame[0].membership,frame[40].membership);});
test('invalid forms and resolver states fail explicitly',()=>{const {node}=fixture();assert.throws(()=>morphFrame(node,{form:'invented'}));assert.throws(()=>morphFrame(node,{resolveState:()=>({holdingStrength:NaN})}));});
test('renderer escapes symbols and preserves occurrence markers',()=>{const {graph,node}=fixture(),root={innerHTML:''};const view=new SwarmMorphView({root,graph});view.render({compositionId:node.id,form:'chair'});assert.match(root.innerHTML,/&lt;/);assert.match(root.innerHTML,/data-occurrence-id="letter-0"/);});
