import test from 'node:test';
import assert from 'node:assert/strict';
import {SymbolCompositionGraph} from '../components/organism/integration/SymbolCompositionGraph.mjs';
import {morphFrame,SwarmMorphView,dimensionalOffset} from '../components/organism/browser/SwarmMorphView.mjs';
function fixture(){const graph=new SymbolCompositionGraph();const ids=Array.from('I am a person who remembers').map((symbol,i)=>{const id=`letter-${i}`;graph.occurrence({id,symbol,address:{gate:1,dimension:'Being'}});return id;});return {graph,node:graph.compose(ids)};}
test('opaque surface placements retain the graph constituents in each form',()=>{const {graph,node}=fixture(),before=graph.snapshot();for(const form of ['chair','house','person','body','world','page']){const frame=morphFrame(node,{form});assert.ok(frame.length>20);assert.ok(frame.every(p=>p.opacity===1));assert.ok(frame.every(p=>p.constituentIds.every(id=>graph.get(id))));assert.equal(frame[0].addresses[0].gate,1);}assert.deepEqual(graph.snapshot(),before);});
test('word filter exposes the same placements without changing their state',()=>{const {graph,node}=fixture(),root={innerHTML:''},view=new SwarmMorphView({root,graph});const before=view.render({compositionId:node.id,form:'chair'});assert.match(root.innerHTML,/<rect/);assert.doesNotMatch(root.innerHTML,/<text/);const after=view.setWordFilter(true);assert.match(root.innerHTML,/<text/);assert.deepEqual(after.particles,before.particles);});
test('confirmed dimension directions are applied without guessing others',()=>{assert.deepEqual(dimensionalOffset('Movement',0),{x:0,y:100});assert.deepEqual(dimensionalOffset('Movement',1),{x:0,y:0});assert.deepEqual(dimensionalOffset('Being',0),{x:-100,y:0});assert.deepEqual(dimensionalOffset('Evolution',0),{x:0,y:0});assert.deepEqual(dimensionalOffset('Design',0,{Design:[50,50]}),{x:50,y:50});});
test('weak support deforms rather than deletes or makes words transparent',()=>{const {node}=fixture();const strong=morphFrame(node,{form:'house'}),weak=morphFrame(node,{form:'house',resolveState:()=>({holdingStrength:0})});assert.equal(weak.length,strong.length);assert.deepEqual(weak[0].constituentIds,strong[0].constituentIds);assert.notEqual(weak[0].y,strong[0].y);assert.equal(weak[0].opacity,1);});
test('person resolver receives sensory input and the exact constituent address',()=>{const {graph,node}=fixture(),root={innerHTML:''},sensory={emotion:'calm',sensation:'warm'};let seen;const view=new SwarmMorphView({root,graph,readSensory:()=>sensory,resolveState:(occurrence,context)=>{seen={occurrence,context};return {holdingStrength:1,emotion:context.sensory.emotion};}});const frame=view.render({compositionId:node.id,form:'person'});assert.equal(seen.context.sensory,sensory);assert.equal(seen.occurrence.address.gate,1);assert.equal(frame.particles[0].states[0].emotion,'calm');});
test('invalid holding strength and unknown forms fail explicitly',()=>{const {node}=fixture();assert.throws(()=>morphFrame(node,{form:'unknown'}));assert.throws(()=>morphFrame(node,{resolveState:()=>({holdingStrength:NaN})}));});
