const DB='synthia-knowledge-v1', VER=1;
const reqP=req=>new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)});
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('docs'))db.createObjectStore('docs',{keyPath:'id'});if(!db.objectStoreNames.contains('chunks')){const s=db.createObjectStore('chunks',{keyPath:'id'});s.createIndex('docId','docId');}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function digest(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const tokens=s=>new Set(String(s).toLowerCase().match(/[a-z0-9_-]{3,}/g)||[]);
export class KnowledgeVault{
 async ingestFile(file,{chunkSize=8000}={}){const text=await file.text();const hash=await digest(text);const id=`doc:${hash}`;const db=await openDB();const tx=db.transaction(['docs','chunks'],'readwrite');const docs=tx.objectStore('docs'),chunks=tx.objectStore('chunks');docs.put({id,hash,name:file.name,type:file.type||'text/plain',size:file.size,createdAt:Date.now(),chars:text.length});let n=0;for(let i=0;i<text.length;i+=chunkSize){const part=text.slice(i,i+chunkSize);chunks.put({id:`${id}:chunk:${n}`,docId:id,index:n,text:part,chars:part.length});n++;}await new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});return {id,hash,name:file.name,size:file.size,chunks:n,chars:text.length}}
 async list(){const db=await openDB();return reqP(db.transaction('docs').objectStore('docs').getAll())}
 async search(query,{limit=4}={}){const q=tokens(query);if(!q.size)return[];const db=await openDB(),all=await reqP(db.transaction('chunks').objectStore('chunks').getAll()),docs=await this.list(),byId=new Map(docs.map(d=>[d.id,d]));return all.map(c=>{const t=tokens(c.text);let overlap=0;for(const x of q)if(t.has(x))overlap++;return {...c,score:overlap/Math.max(1,q.size),source:byId.get(c.docId)?.name||c.docId}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.index-b.index).slice(0,limit)}
 async exportAll(){const db=await openDB();return {version:1,docs:await reqP(db.transaction('docs').objectStore('docs').getAll()),chunks:await reqP(db.transaction('chunks').objectStore('chunks').getAll())}}
 async importAll(payload){if(!payload?.docs||!payload?.chunks)throw new Error('invalid knowledge export');const db=await openDB(),tx=db.transaction(['docs','chunks'],'readwrite');for(const d of payload.docs)tx.objectStore('docs').put(d);for(const c of payload.chunks)tx.objectStore('chunks').put(c);await new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});return {docs:payload.docs.length,chunks:payload.chunks.length}}
}
export default KnowledgeVault;
