const DB='synthia-validated-learning-v1', VER=1;
const STORES=['observations','normalizations','relations','claims','claimRelations','corrections','mesh','meta'];
const reqP=req=>new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)});
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const db=r.result;for(const name of STORES){if(!db.objectStoreNames.contains(name))db.createObjectStore(name,{keyPath:'id'});}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function digest(text){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const CLAUSE=/\b(?<subject>[A-Za-z][A-Za-z '\-]{0,70}?)\s+(?<predicate>is|are|was|were|means?|becomes?|creates?|connects?|expresses?)\s+(?<object>[^.;!?]{2,220})/gi;
const KNOWN_OCR=[['l1iould','would'],['l1ould','would'],['!dusic','music'],['idus ic','music'],['hullleln','human'],['huinan','human'],['des1gn','design']];
const clone=v=>structuredClone(v);
function normalizeOCR(text){let revised=String(text).replace(/\u00ad/g,''),repairs=[];const joined=revised.replace(/(?<=\w)-\s*\n\s*(?=[a-z])/g,'');if(joined!==revised){repairs.push('joined line-break hyphenation');revised=joined;}for(const [bad,good] of KNOWN_OCR){const re=new RegExp(bad.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'ig');if(re.test(revised)){re.lastIndex=0;revised=revised.replace(re,good);repairs.push(`${bad}->${good}`);}}const spaced=revised.replace(/[ \t]{2,}/g,' ');if(spaced!==revised){repairs.push('normalized spacing');revised=spaced;}return {text:revised,repairs};}
function normalizationConfidence(original,normalized){const suspicious=[...normalized].filter(c=>/\d|!|\|/.test(c)).length;const ratio=suspicious/Math.max(1,normalized.length);const change=Math.abs(original.length-normalized.length)/Math.max(1,original.length);return Math.round(Math.max(.3,Math.min(.99,.96-ratio*8-change*2))*1000)/1000;}
async function all(store){const db=await openDB();return reqP(db.transaction(store).objectStore(store).getAll())}
async function put(store,value){const db=await openDB();const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);return new Promise((res,rej)=>{tx.oncomplete=()=>res(value);tx.onerror=()=>rej(tx.error)})}
async function get(store,id){const db=await openDB();return reqP(db.transaction(store).objectStore(store).get(id))}
export class ValidatedLearningStore{
  constructor({onAccepted=null}={}){this.onAccepted=onAccepted;}
  async ingest(sourceId,location,text){const checksum=await digest(text),id=`obs:${await digest(`${sourceId}\0${location}\0${checksum}`)}`;const existing=await get('observations',id);if(existing)return existing;const observation={id,sourceId,location:String(location),originalText:String(text),checksum,observedAt:Date.now()};await put('observations',observation);return observation;}
  async normalize(observationId,{engineVersion='AUTOLING-v2'}={}){const observation=await get('observations',observationId);if(!observation)throw new Error('Unknown observation');const {text,repairs}=normalizeOCR(observation.originalText);const confidence=normalizationConfidence(observation.originalText,text);const previous=(await all('normalizations')).filter(n=>n.observationId===observationId);const version=1+Math.max(0,...previous.map(n=>Number(n.version||0)));const id=`norm:${await digest(`${observationId}\0${version}\0${text}`)}`;const normalization={id,observationId,version,normalizedText:text,confidence,reason:`${engineVersion}: ${repairs.join(', ')||'no repair'}`,status:confidence>=.72?'accepted':'pending',supersedes:null,createdAt:Date.now()};await put('normalizations',normalization);return normalization;}
  async extractAndValidate(normalizationId){const n=await get('normalizations',normalizationId);if(!n)throw new Error('Unknown normalization');const compact=n.normalizedText.replace(/\s+/g,' '),out=[];CLAUSE.lastIndex=0;let m;while((m=CLAUSE.exec(compact))){const subject=m.groups.subject.trim(),predicate=m.groups.predicate.trim().toLowerCase(),object=m.groups.object.trim();const malformed=/[\d!|]/.test(subject+object);const confidence=n.confidence*(malformed?.55:.94);const status=n.status==='accepted'&&confidence>=.68?'approved':'quarantined';const id=`rel:${await digest(`${normalizationId}\0${subject}\0${predicate}\0${object}`)}`;const rel={id,normalizationId,subject,predicate,object,confidence,status,active:true,createdAt:Date.now()};await put('relations',rel);out.push(rel);if(status==='approved'&&this.onAccepted)await this.onAccepted(clone(rel));}return out;}
  async writeClaimsForRelations(relations){const out=[];for(const r of relations.filter(x=>x.status==='approved'&&x.active)){const id=`claim:${await digest(r.id)}`;const claim={id,topic:r.subject,text:`${r.subject} ${r.predicate} ${r.object}`,active:true,createdAt:Date.now()};await put('claims',claim);await put('claimRelations',{id:`${id}::${r.id}`,claimId:id,relationId:r.id});out.push(claim);}return out;}
  async processText(sourceId,location,text){const observation=await this.ingest(sourceId,location,text);const normalization=await this.normalize(observation.id);const relations=await this.extractAndValidate(normalization.id);const claims=await this.writeClaimsForRelations(relations);return {observation,normalization,relations,claims};}
  async traceClaim(claimId){const links=(await all('claimRelations')).filter(x=>x.claimId===claimId),trace=[];for(const link of links){const r=await get('relations',link.relationId);if(!r)continue;const n=await get('normalizations',r.normalizationId);const o=n&&await get('observations',n.observationId);if(o)trace.push({claimId,relation:r,normalization:n,observation:o});}return trace;}
  async correctNormalization(normalizationId,correctedText){const before=await get('normalizations',normalizationId);if(!before)throw new Error('Unknown normalization');before.status='superseded';await put('normalizations',before);for(const r of (await all('relations')).filter(x=>x.normalizationId===normalizationId)){r.active=false;await put('relations',r);}const id=`norm:${await digest(`${before.observationId}\0${before.version+1}\0${correctedText}`)}`;const after={...before,id,version:before.version+1,normalizedText:String(correctedText),confidence:1,reason:'residence correction',status:'accepted',supersedes:normalizationId,createdAt:Date.now()};await put('normalizations',after);const correction={id:`correction:${await digest(`${normalizationId}\0${id}`)}`,targetId:normalizationId,before:clone(before),after:clone(after),active:true,createdAt:Date.now()};await put('corrections',correction);const relations=await this.extractAndValidate(id);await this.writeClaimsForRelations(relations);return correction;}
  async status(){const [observations,normalizations,relations,claims,corrections]=await Promise.all(['observations','normalizations','relations','claims','corrections'].map(all));const approved=relations.filter(x=>x.active&&x.status==='approved').length,quarantined=relations.filter(x=>x.active&&x.status==='quarantined').length;return {sourceObservations:observations.length,normalizations:normalizations.length,relations:relations.length,approvedRelations:approved,quarantinedRelations:quarantined,activeClaims:claims.filter(x=>x.active).length,corrections:corrections.length};}
  async claims(limit=100){return (await all('claims')).filter(x=>x.active).slice(-limit).reverse();}
}
export default ValidatedLearningStore;
